### ISSUE TITLE
Are all unit tests passing?

### ISSUE THREAD

**Issue by LegalizeAdulthood** [acli/trn#26]
I merged your changes to [my fork](https://github.com/LegalizeAdulthood/trn) and they applied cleanly to my master (which is trn4.0test77 from sourceforge).  Then I rebased my current work in my `cmake` branch on top of your changes.  In the process of integrating your unit tests into the ones that I had added, I am getting the following failures in gtest:

```
[ RUN      ] TerminateStringAtVisualIndexTest.iso8859_1
C:\Code\trn\trn\tests\trn\test_utf.cpp(405): error: Expected equality of these values:
  m_after
    Which is: "\xC3\xA1\xC3\xAD\xC3\xBA\xC3\xA9\xC3\xB3"
    As Text: "├í├¡├║├⌐├│"
  m_buffer
    Which is: "\xC3\xA1\xC3\xAD\xC3\xBA"
    As Text: "├í├¡├║"
terminate_string_at_visual_index(5)
[  FAILED  ] TerminateStringAtVisualIndexTest.iso8859_1 (11 ms)
[ RUN      ] TerminateStringAtVisualIndexTest.cjk_basic
C:\Code\trn\trn\tests\trn\test_utf.cpp(416): error: Expected equality of these values:
  m_after
    Which is: "\xAF\xA7\xE5\x8C\x96\xE9\xA3\x9B\xE7\x81\xB0"
  m_buffer
    Which is: "\xAF\xA7\xE5\x8C\x96\xE9\xA3\x9B\xE7\x81\xB0\xE4"
terminate_string_at_visual_index(8)
[  FAILED  ] TerminateStringAtVisualIndexTest.cjk_basic (2977 ms)
[ RUN      ] TerminateStringAtVisualIndexTest.cjk_basic_at_wrong_boundary
C:\Code\trn\trn\tests\trn\test_utf.cpp(427): error: Expected equality of these values:
  m_after
    Which is: "\xE5\xAF\xA7\xE5\x8C\x96\xE9\xA3\x9B\xE7\x81\xB0 "
    As Text: "σ»ºσîûΘú¢τü░ "
  m_buffer
    Which is: "\xE5\xAF\xA7\xE5\x8C\x96\xE9\xA3\x9B\xE7\x81\xB0\xE4"
terminate_string_at_visual_index(9)
[  FAILED  ] TerminateStringAtVisualIndexTest.cjk_basic_at_wrong_boundary (3 ms)
```

My assumption is that I missed something when I was rebasing my changes on top of yours, but I wanted to check to see if you get a clean test run on your tree.  I am developing on Windows, so I don't have ready access to a unix machine right now.  I'm going to see what I can do under WSL, but that's a whole other journey....

**Comment by acli** [comment]
I checked out a fresh copy of my fork and tried to build it. The unit tests are passing on my end, but it is possible my coding is too sloppy and some of the stuff I wrote might not be portable.

I took a look at utf8.c (I haven’t touched trn for a long time). I’m suspecting const char * in byte_length_at and visual_width_at might be the issue.  Is char a signed type on Windows?

**Comment by LegalizeAdulthood** [comment]
That's a good idea, I'll take a look tonight.  Thanks for the quick reply!

**Comment by LegalizeAdulthood** [comment]
OK, on MSVC `char` is signed, but when I hacked up things to use `unsigned char` (via typedef `Uchar`), I still got failures.  I'm going to try your tests on WSL without my changes and see if they pass.  That will give me a baseline to compare against.

**Comment by LegalizeAdulthood** [comment]
OK, after using WSL and beating on the generated `config.h` and `Makefile` (how do modern linux package maintainers build this crufty old code? LOL), I was able to run your tests on my `master` branch and they all pass.  So things are still pointing to signed/unsigned differences, or potential merge errors on my cmake branch.

**Comment by LegalizeAdulthood** [comment]
It must be something in my merge or in my CMake build environment because I get the same failures in WSL on my cmake branch but things pass on master under WSL.

**Comment by LegalizeAdulthood** [comment]
OK, it was an error on my part when I was converting raw non-ASCII characters to octal character escapes.  Now all the UTF tests are passing on my cmake branch.  Thank you for writing these tests!

**Comment by LegalizeAdulthood** [comment]
BTW, after porting the rest of your tests, I added more covering tests to `compress_name` based on the comment on the function and found some bugs in that function that I haven't yet fixed.  I tried disabling the UTF hack macro and the same tests failed, so I think these bugs were there all along.  It would probably be a good idea to add some test cases to `compress_name` for non-ASCII strings to cover the UTF changes.

**Comment by LegalizeAdulthood** [comment]
These are [the new tests I added](https://github.com/LegalizeAdulthood/trn/blob/c2fd505ae3a0bfec308dfe1a5dc577f84ef50a0c/tests/trn/test_rt-util.cpp); the `DISABLED_` tests are the ones that are failing.

**Comment by acli** [comment]
> how do modern linux package maintainers build this crufty old code? LOL

i honestly don’t know. when you reported the problem i tried to do a clean make and i couldn’t get it to work; i had to look at my old config.h. i have no idea how i managed to get a config.h three years ago

**Comment by LegalizeAdulthood** [comment]
With the switch to CMake and dropping all the legacy options for old crufty unixes that are all "the same but different", things should get much easier for them.
